#!/usr/bin/with-contenv bash

TFA_MODE=${TFA_MODE:-""}
DUO_i_KEY=${DUO_i_KEY:-""}
DUO_s_KEY=${DUO_s_KEY:-""}
DUO_a_KEY=${DUO_a_KEY:-""}
DUO_API_HOST=${DUO_API_HOST:-""}
DUO_POST_ACTION_URL=${DUO_POST_ACTION_URL:-""}


# make folders
mkdir -p \
	/config/remote/ \
	
cd /defaults/remote-conf || exit
shopt -s globstar nullglob

[[ ! -e /config/remote/config.php ]] && \
	cp /defaults/remote-conf/config.php /config/remote/config.php
	
[[ ! -e /app/remote/config.php ]] && \
	ln -s /config/remote/config.php /app/remote/config.php
	
# delete the default directories from linuxserver:docker-rutorrent
rm -fr \
	/downloads/completed \
	/downloads/incoming \
	/downloads/watched

echo "**** check 2FA env ****"
if [ "$TFA_MODE" == "DUO" ] 
then
	cd /defaults/duo-conf || exit
	
	[[ ! -e /app/remote/inc/duo.php ]] && \
	cp /defaults/duo-conf/duo.php /app/remote/inc/duo.php
	
	[[ ! -e /app/remote/js/Duo-Web-v2.min.js ]] && \
	cp /defaults/duo-conf/Duo-Web-v2.min.js /app/remote/js/Duo-Web-v2.min.js
	
	# copy (overwrite) default 2fa login.php to app dir
	cp -rf /defaults/duo-conf/login.php /app/remote/inc/login.php
	
	# substitude individual params with environment vars
	sed -i -e 's!%DUO_i_KEY%!'"$DUO_i_KEY"'!g' /app/remote/inc/login.php
	sed -i -e 's!%DUO_s_KEY%!'"$DUO_s_KEY"'!g' /app/remote/inc/login.php
	sed -i -e 's!%DUO_a_KEY%!'"$DUO_a_KEY"'!g' /app/remote/inc/login.php
	sed -i -e 's!%DUO_API_HOST%!'"$DUO_API_HOST"'!g' /app/remote/inc/login.php
	sed -i -e 's!%DUO_POST_ACTION_URL%!'"$DUO_POST_ACTION_URL"'!g' /app/remote/inc/login.php	
fi

chown -R abc:abc \
	/config/remote \
	/app/remote
	
echo "**** restart nginx ****"
rc-service nginx stop
rc-service nginx start